language: minimal

services:
  - docker

script:
  - docker build -t plus64nz/sip-registrar-kamailio kamailio

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push plus64nz/sip-registrar-kamailio
  on:
    branch: master
