apiVersion: v1
kind: Service
metadata:
  name: sip-registrar
  labels:
    app: sip-registrar
    tier: middle
spec:
  ports:
  - name: sip
    port: 5060
    targetPort: 5060
    nodePort: 30876
  - name: sip-tls
    port: 5061
    targetPort: 5061
    nodePort: 30877
  selector:
    app: sip-registrar
    tier: middle
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sip-registrar
spec:
  selector:
    matchLabels:
      app: sip-registrar
      tier: middle
  replicas: 1
  template:
    metadata:
      labels:
        app: sip-registrar
        tier: middle
    spec:
      containers:
      - name: sip-registrar-kamailio
        image: plus64nz/sip-registrar-kamailio:latest
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 5061
